### ISSUE TITLE
PSR4 support

### ISSUE THREAD

**Issue by arnolanglade** [memio/spec-gen#9]
When I enable the extension and I configure phpspec with PSR4 the generated spec follows PSR0.

My configuration:
```yaml
suites:
    extensions:
        Memio\SpecGen\MemioSpecGenExtension: ~

    Polymorphism:
        namespace: Al\Polymorphism
        psr4_prefix: Al\Polymorphism
```

When I describe a class:
```bash
psdesc "Al\Polymorphism\Integer"
Specification for Al\Polymorphism\Integer created in /home/arnaud/www/polymorphisme/spec/Al/Polymorphism/IntegerSpec.php.

```
Do I something wrong?
